apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Values.PrimaryName}}"
  labels:
    app: "{{.Values.PrimaryName}}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
{{ (.Files.Glob "files/cluster/*").AsConfig | indent 2 }}
