kind: Service
apiVersion: v1
metadata:
  name: "{{.Values.Container.Name.Primary}}"
  labels:
    name: "{{.Values.Container.Name.Primary}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: "{{.Values.ServiceType}}"
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: "{{.Values.Container.Name.Primary}}"
  sessionAffinity: None
