apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.PrimaryName}}"
  labels:
    name: "{{.Values.PrimaryName}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - port: 5432
    name: web
  clusterIP: None
  selector:
    app: "{{.Values.PrimaryName}}"
