apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: "{{.Values.Container.Name.Primary}}"
  labels:
    name: "{{.Values.Container.Name.Replica}}"
    app: "{{.Values.Container.Name.Primary}}"
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  selector:
    matchLabels:
      app: "{{.Values.Container.Name.Primary}}"
  serviceName: "{{.Values.Container.Name.Primary}}"
  replicas: 2
  template:
    metadata:
      labels:
        app: "{{.Values.Container.Name.Primary}}"
    spec:
      serviceAccount: "{{.Values.Container.ServiceAccount}}"
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{.Values.Container.Name.Primary}}
        image: "{{.Values.Image.Repository}}/{{.Values.Image.Container}}:{{.Values.Image.Tag}}"
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PGHOST
          value: /tmp
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PG_MODE
          value: set
        - name: PG_PRIMARY_HOST
          value: "{{.Values.Container.Name.Primary}}"
        - name: PG_PRIMARY_PORT
          value: "5432"
        - name: PG_PRIMARY_PASSWORD
          value: "{{.Values.Credentials.Primary}}"
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: "{{.Values.Credentials.User}}"
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: "{{.Values.Credentials.Root}}"
        volumeMounts:
        - name: pgdata
          mountPath: "/pgdata"
          readOnly: false
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: {{.Values.PVC.Name}}
