---
kind: Service
apiVersion: v1
metadata:
  name: "{{.Values.PrimaryName}}-replica"
  labels:
    name: "{{.Values.PrimaryName}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: "{{.Values.PrimaryName}}-replica"
  type: ClusterIP
  sessionAffinity: None
