apiVersion: v1
name: statefulset
description: This example deploys a statefulset named pgset.
version: 1.6.0
keywords:
- postgresql
- postgres
- database
- sql
home: https://www.crunchydata.com/
icon: http://trusted-charts-logos.stackpoint.io/crunchy_logo.png
sources:
- https://github.com/CrunchyData/crunchy-containers
