apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{.Values.Containers.Name.Replica}}"
  labels:
    name: "{{.Values.Containers.Name.Replica}}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "{{.Values.Containers.Name.Replica}}"
  template:
    metadata:
      labels:
        name: "{{.Values.Containers.Name.Replica}}"
      name: "{{.Values.Containers.Name.Replica}}"
    spec:
      containers:
      - env:
        - name: PGHOST
          value: /tmp
        - name: PG_PRIMARY_HOST
          value: "{{.Values.Container.Name.Primary}}"
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PG_MODE
          value: replica
        - name: PG_PRIMARY_PORT
          value: "5432"
        - name: PG_PRIMARY_PASSWORD
          value: "{{.Values.Credentials.Primary}}"
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: "{{.Values.Credentials.User}}"
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: "{{.Values.Credentials.Root}}"
        image: image: "{{.Values.Image.Repository}}/{{.Values.Image.Container}}:{{.Values.Image.Tag}}"
        imagePullPolicy: IfNotPresent
        name: "{{.Values.Containers.Name.Replica}}"
        ports:
        - containerPort: 5432
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /pgdata
          name: pgdata
        - mountPath: /backup
          name: backup
          readOnly: true
        - mountPath: /pguser
          name: pguser-volume
        - mountPath: /pgprimary
          name: pgprimary-volume
        - mountPath: /pgroot
          name: pgroot-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: pgdata
      - emptyDir: {}
        name: backup
      - name: pguser-volume
        secret:
         secretName: pguser-secret
      - name: pgprimary-volume
        secret:
         secretName: pgprimary-secret
      - name: pgroot-volume
        secret:
         secretName: pgroot-secret
