# This is a service gateway to the replica set created by the deployment.
# Take a look at the deployment.yaml for general notes about this chart.
apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.container.name.Replica}}"
  labels:
    name: "{{.Values.container.name.Replica}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.name | quote }}
    chart: "{{.Chart.name}}-{{.Chart.Version}}"
spec:
  type: "{{.Values.serviceType}}"
  ports:
  - port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
    protocol: TCP
    name: postgres
  selector:
    name: "{{.Values.container.name.Replica}}"
