---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: "{{.Values.PrimaryName}}"
  name: pv2
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  nfs:
    path: "$PV_PATH"
    server: "$LOCAL_IP"
  persistentVolumeReclaimPolicy: Retain
