apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: "{{.Values.ContainerName}}"
  name: "{{.Values.PVName}}-2"
spec:
  capacity:
    storage: 150M
  accessModes:
  - ReadWriteMany
  nfs:
    path: "$PV_PATH"
    server: "$LOCAL_IP"
  persistentVolumeReclaimPolicy: Retain
