kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.pvc.name}}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{.Values.persistence.size | quote }}
