apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.PrimaryName}}"
  labels:
    name: "{{.Values.PrimaryName}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: "{{.Values.ServiceType}}"
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
    name: postgres
  selector:
    name: "{{.Values.PrimaryName}}"
  type: ClusterIP
  sessionAffinity: None
